name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0  # Ensure full history is available

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/NSCC-ITC-Winter2025-WEBD5015-700-MCa/webd5015-project-mystery-meal.git
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories

      - name: Push to forked repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push origin main
